### ISSUE TITLE
很奇怪，result反馈回来的数据总是<Response [200]>

### ISSUE THREAD

**Issue by davidelectricfree** [TkzcM/CCCAT-checkin#1]
编辑掉

**Comment by TkzcM** [comment]
是直接用的这个 py 吗？因为站点登录加了 hCaptcha，所以已经失效了。

**Comment by davidelectricfree** [comment]
> 是直接用的这个 py 吗？因为站点登录加了 hCaptcha，所以已经失效了。

肯定不能直接用，代码逻辑改过了，你之前是使用账号密码登录，记住cookie，通过记住的cookie直接去登录checkin，同时用json()得到网页给出的msg信息，我这边改成预设cookie，编好header，通过这种方式可以登陆，可以跳过他的验证，也可以checkin，但是代码里的用json()得到网页给出的msg信息，会始终显示错误。

**Comment by davidelectricfree** [comment]
> 是直接用的这个 py 吗？因为站点登录加了 hCaptcha，所以已经失效了。

今天有抽时间搞了下，发现，get回来的数据，text全部是乱码，json直接是报错，我上浏览器里用开发者看了下，好像服务器那边在里面插了一张图，有没有可能是这个图导致的json()无法正常作用呢，大佬现在没有自动签到了吗？

**Comment by TkzcM** [comment]
站点现在禁止中国大陆访问，换个IP吧

**Comment by davidelectricfree** [comment]
> 站点现在禁止中国大陆访问，换个IP吧

大佬，我能够登录，也能够签到成功，但是我想把他那个弹窗信息的msg采集出来，现在卡在那一步，我前面说的都是卡在那一步的情况。

**Comment by davidelectricfree** [comment]
> 站点现在禁止中国大陆访问，换个IP吧

我想知道我签到获得多少流量，那个流量就是那个弹窗出来的消息，现在就是那个消息我抓不到。

**Comment by davidelectricfree** [comment]
> 站点现在禁止中国大陆访问，换个IP吧

我现在已经把整个程序做好了，包括简单成功以后会自动发信息给server酱那边，这个也做好了，但是现在整个程序还差我只知道签到成功了，但是不知道究竟签到获得多少流量，这个信息我抓不到，现在是这个问题

**Comment by TkzcM** [comment]
```python
checkin = requests.get('https://cccat.io/user/_checkin.php', cookies=cookies,verify=False)
results = checkin.json()
if results.get('msg') == 'You have already checked in':
    print('checked')
else:
    prize = results.get('msg').split()
    print(prize[1])
```

**Comment by davidelectricfree** [comment]
> ```python
> checkin = requests.get('https://cccat.io/user/_checkin.php', cookies=cookies,verify=False)
> results = checkin.json()
> if results.get('msg') == 'You have already checked in':
>     print('checked')
> else:
>     prize = results.get('msg').split()
>     print(prize[1])
> ```

​results​ ​=​ ​checkin​.​json​()实际运行是会报错的，你可以试试

**Comment by TkzcM** [comment]
刚试的呀，可以正常返回流量和是否已签到

**Comment by davidelectricfree** [comment]
> ```python
> checkin = requests.get('https://cccat.io/user/_checkin.php', cookies=cookies,verify=False)
> results = checkin.json()
> if results.get('msg') == 'You have already checked in':
>     print('checked')
> else:
>     prize = results.get('msg').split()
>     print(prize[1])
> ```
> 
> 我用这个是完全没有问题的

我刚试过，本机+github action都跑不起来，会报错

**Comment by davidelectricfree** [comment]
> 刚试的呀，可以正常返回流量和是否已签到

这。。。

**Comment by davidelectricfree** [comment]
> 刚试的呀，可以正常返回流量和是否已签到

我自己研究下吧，服了

**Comment by davidelectricfree** [comment]
> 刚试的呀，可以正常返回流量和是否已签到

另外，感谢这么晚还回复，晚安，明天再研究研究
